# Generated by Django 5.2.15 on 2026-06-16 09:16

import backend.schedule.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_certificate_images_alter_doctor_image'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='is_24_7',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('blocked', 'Blocked'), ('booked', 'Booked')], default='available', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='doctors.doctor')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['doctor', 'date', 'status'], name='schedule_ti_doctor__a0e130_idx'), models.Index(fields=['doctor', 'date', 'start_time'], name='schedule_ti_doctor__ed9dae_idx')],
                'unique_together': {('doctor', 'date', 'start_time')},
            },
            managers=[
                ('objects', backend.schedule.models.TimeSlotManager()),
            ],
        ),
    ]
