# Generated by Django 5.1.4 on 2026-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('is_24_7', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clinics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
