# Generated by Django 5.2.15 on 2026-06-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_latitude_clinic_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='formatted_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
