# Generated by Django 5.2.15 on 2026-06-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certificate_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(null=True, upload_to='doctors/'),
        ),
    ]
