# Generated by Django 5.2.15 on 2026-06-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_certificate_images_alter_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patient_type',
            field=models.CharField(choices=[('adults', 'Kattalar'), ('children', 'Bolalar'), ('both', 'Ikkalasi')], default='both', max_length=10),
        ),
    ]
