# Generated by Django 5.2.1
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I+", "I+"),
                    ("I-", "I-"),
                    ("II+", "II+"),
                    ("II-", "II-"),
                    ("III+", "III+"),
                    ("III-", "III-"),
                    ("IV+", "IV+"),
                    ("IV-", "IV-"),
                ],
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
            ),
        ),
    ]
