# Generated by Django 5.2.15 on 2026-06-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_blood_group_user_allergies_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
